# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senery', '0002_auto_20170807_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_url',
            field=models.CharField(max_length=128),
        ),
    ]
